#!/bin/sh
cd /usr/local/www/librenms

# Wait for database tables to exist before starting dispatcher
while ! s6-setuidgid bsd php artisan config:get fping >/dev/null 2>&1; do
    echo "[dispatcher] waiting for LibreNMS database initialization..."
    sleep 5
done

printf '\n' >&3
exec s6-setuidgid bsd python3 librenms-service.py
